# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

os:
  - linux
#  - osx
# add back osx later with clean solution for openmp/rcpparmadillo

r: release

warnings_are_errors: false