# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

os:
  - linux
#  - osx
# add back osx later with clean solution for openmp/rcpparmadillo

r: release

env:
  global:
    - HDF5_VERSION=1.10.2
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"

warnings_are_errors: false