# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

os:
  - linux
  # - osx
# add back osx later with clean solution for openmp/rcpparmadillo

r: release

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

warnings_are_errors: false
